In [3]:
import pandas as pd

In [4]:
sp = pd.read_excel(r"Z:\Калинкина\Вернувшиеся 13.03.2026.xls")

In [5]:
tfoms = pd.read_csv(r'h:\СЦ\ТФОМС\Flyagina_tfoms\all_for_tfoms.csv')

C:\Users\koreshilova_ea\AppData\Local\Temp\ipykernel_17764\520443147.py:1: DtypeWarning: Columns (2) have mixed types. Specify dtype option on import or set low_memory=False.
  tfoms = pd.read_csv(r'h:\СЦ\ТФОМС\Flyagina_tfoms\all_for_tfoms.csv')

In [54]:
sp

,№ п/п,ФИО,Дата_рождения,СНИЛС,Телефон домашний,Телефон мобильный,Дополнительные телефоны,Район/организация,fio,DR
0,1,Абайдулин Артур Юристович,1979-11-02,106-211-270 92,NaN,NaN,NaN,Город Тюмень,абайдулинартурюристович,19791102
1,2,Абакиров Михаил Владимирович,1989-07-25,139-717-428 94,NaN,9.894215e+09,NaN,Город Ишим,абакировмихаилвладимирович,19890725
2,3,Абатуров Андрей Николаевич,1992-04-19,NaN,NaN,9.199380e+09,NaN,Исетский район,абатуровандрейниколаевич,19920419
3,4,Абдрахманов Андрей Аманжолович,1975-12-04,075-919-948 27,NaN,9.123827e+09,NaN,город Ялуторовск,абдрахмановандрейаманжолович,19751204
4,5,Абдужамилов Азамджон Шарифбекович,1991-07-30,170-908-079 73,89698000045,9.320228e+09,+7(922) 267-7731 - жена,Город Тюмень,абдужамиловазамджоншарифбекович,19910730
...,...,...,...,...,...,...,...,...,...,...
1921,1922,Яхин Азис Азатович,1993-11-23,149-136-563 78,9969465032,NaN,NaN,Город Тюмень,яхиназисазатович,19931123
1922,1923,Яцык Андрей Дмитриевич,1989-07-30,155-281-443 62,8-932-625-28-89,NaN,NaN,Город Тюмень,яцыкандрейдмитриевич,19890730
1923,1924,Яшкин Нурлан Бауржанович,1996-07-13,156-078-328 78,NaN,NaN,NaN,Омутинский район,яшкиннурланбауржанович,19960713
1924,1925,Яшкин Раймжан Бауржанович,1991-07-20,141-355-248 32,NaN,9.504883e+09,NaN,Город Тюмень,яшкинраймжанбауржанович,19910720
1925,1926,Яшкина Ольга Васильевна,1960-03-27,065-347-358 75,8-992-302-6503,9.044744e+09,Корректировка мобильного телефона/домашнего/em...,Бердюжский район,яшкинаольгавасильевна,19600327

In [55]:
sp['fio'] = sp['ФИО'].str.lower().str.replace(' ', '').str.replace('ё', "е").str.replace('-', '')

In [56]:
table = str.maketrans('ё', "е", ' -')

In [57]:
tfoms1 = tfoms.copy()

In [58]:
tfoms1['fio'] = tfoms1['FAM'] + tfoms1['IM'] + tfoms1['OT']

In [59]:
tfoms1['fio'] = tfoms1['fio'].str.lower()

In [60]:
tfoms1['fio'] = tfoms1['fio'].str.translate(table)

In [61]:
tfoms1 = tfoms1[['ИД_МО', 'Дата прикрепления', 'DR', 'fio']]

In [62]:
tfoms1['DR'] = tfoms1['DR'].astype(str)

In [63]:
tfoms1['DR'] = tfoms1['DR'].str.split('.', expand=True)[0]

In [64]:
tfoms.head()

,Тип_ДПФС,ИД_полиса,ЕНП,ИД_МО,Способ прикрепления,Тип прикрепления,Дата прикрепления,Дата открепления,FAM,IM,OT,DR
0,3,NaN,7290399796000040,720060,2,1,20241202,NaN,Абабкова,Валерия,Сергеевна,20060903.0
1,3,NaN,8153000834000539,720060,2,1,20161007,NaN,Абаслы,Абас,Сабухи Оглы,19990615.0
2,3,NaN,8191799771000295,720060,2,1,20210212,NaN,Абатурова,Софья,Вячеславовна,20020828.0
3,3,NaN,8398499723000201,720060,2,1,20260115,NaN,Аббасов,Аслан,Аллахярович,20050126.0
4,3,NaN,7248700880000221,720060,2,1,20161007,NaN,Аббасова,Айнур,Джамил-Кызы,19921119.0

In [65]:
sp['DR'] = sp['Дата_рождения'].astype(str)

In [66]:
sp['DR'] = sp['DR'].str.replace('-', '')

In [67]:
sp

,№ п/п,ФИО,Дата_рождения,СНИЛС,Телефон домашний,Телефон мобильный,Дополнительные телефоны,Район/организация,fio,DR
0,1,Абайдулин Артур Юристович,1979-11-02,106-211-270 92,NaN,NaN,NaN,Город Тюмень,абайдулинартурюристович,19791102
1,2,Абакиров Михаил Владимирович,1989-07-25,139-717-428 94,NaN,9.894215e+09,NaN,Город Ишим,абакировмихаилвладимирович,19890725
2,3,Абатуров Андрей Николаевич,1992-04-19,NaN,NaN,9.199380e+09,NaN,Исетский район,абатуровандрейниколаевич,19920419
3,4,Абдрахманов Андрей Аманжолович,1975-12-04,075-919-948 27,NaN,9.123827e+09,NaN,город Ялуторовск,абдрахмановандрейаманжолович,19751204
4,5,Абдужамилов Азамджон Шарифбекович,1991-07-30,170-908-079 73,89698000045,9.320228e+09,+7(922) 267-7731 - жена,Город Тюмень,абдужамиловазамджоншарифбекович,19910730
...,...,...,...,...,...,...,...,...,...,...
1921,1922,Яхин Азис Азатович,1993-11-23,149-136-563 78,9969465032,NaN,NaN,Город Тюмень,яхиназисазатович,19931123
1922,1923,Яцык Андрей Дмитриевич,1989-07-30,155-281-443 62,8-932-625-28-89,NaN,NaN,Город Тюмень,яцыкандрейдмитриевич,19890730
1923,1924,Яшкин Нурлан Бауржанович,1996-07-13,156-078-328 78,NaN,NaN,NaN,Омутинский район,яшкиннурланбауржанович,19960713
1924,1925,Яшкин Раймжан Бауржанович,1991-07-20,141-355-248 32,NaN,9.504883e+09,NaN,Город Тюмень,яшкинраймжанбауржанович,19910720
1925,1926,Яшкина Ольга Васильевна,1960-03-27,065-347-358 75,8-992-302-6503,9.044744e+09,Корректировка мобильного телефона/домашнего/em...,Бердюжский район,яшкинаольгавасильевна,19600327

In [68]:
sp_new = sp.merge(tfoms1, how='left', on=['fio', 'DR'])

In [69]:
sp_new['ИД_МО'] = sp_new['ИД_МО'].astype(str)

In [70]:
sp_new['ИД_МО'] = sp_new['ИД_МО'].str.split('.', expand=True)[0]

In [71]:
mo_name = pd.read_excel(r'h:\СЦ\ТФОМС\Flyagina_tfoms\Реестровый номер МО.xlsx')

In [72]:
mo_name['Реестровый номер'] = mo_name['Реестровый номер'].astype(str)

In [73]:
sp_new = sp_new.merge(mo_name, how='left', left_on='ИД_МО', right_on='Реестровый номер')

In [74]:
#sp_new.drop(columns=['fio', 'DR', 'ИД_МО', 'Реестровый номер'], inplace=True)

In [75]:
sp_new['Дата прикрепления'] = sp_new['Дата прикрепления'].astype(str)

In [76]:
sp_new = sp_new.drop_duplicates()

In [77]:
sp_new_null = sp_new[sp_new['mo_name'].isna()]
sp_new_pull = sp_new[~sp_new['mo_name'].isna()]

In [78]:
sp_new_null.head()

,№ п/п,ФИО,Дата_рождения,СНИЛС,Телефон домашний,Телефон мобильный,Дополнительные телефоны,Район/организация,fio,DR,ИД_МО,Дата прикрепления,Реестровый номер,mo_name
17,18,Абсолямов Фаиль Маратович,1993-04-27,148-606-419 79,NaN,NaN,NaN,Город Тюмень,абсолямовфаильмаратович,19930427,nan,nan,NaN,NaN
43,44,Алиев Руслан Вилаятович,1983-07-04,136-488-119 84,NaN,9.966401e+09,NaN,Тобольский район,алиеврусланвилаятович,19830704,nan,nan,NaN,NaN
73,74,Ануфриева Наталья Валерьевна,1987-02-23,129-272-295 71,8-922-780-0216,9.322008e+09,NaN,Вагайский район,ануфриеванатальявалерьевна,19870223,nan,nan,NaN,NaN
94,95,Ахминеев Андрей Иванович,1984-10-28,081-260-065 29,NaN,9.014133e+09,NaN,Город Тобольск,ахминеевандрейиванович,19841028,nan,nan,NaN,NaN
123,124,Барболин Мирослав Иванович,1997-09-26,151-301-644 07,+7(912) 928-0305 быв. жена Анастасия Романовна,9.821350e+09,NaN,Город Тюмень,барболинмирославиванович,19970926,nan,nan,NaN,NaN

In [79]:
sp_new_null = sp_new_null.drop(columns=['ИД_МО', 'Дата прикрепления', 'Реестровый номер', 'mo_name'])

In [80]:
tfy = pd.read_csv(r'h:\СЦ\ТФОМС\Flyagina_tfoms\TF_2\TFY_100326_01.csv', encoding='cp1251', sep=';', index_col=False, low_memory=False)

In [81]:
tfy['fio'] = tfy['FAM'] + tfy['IM'] + tfy['OT']

In [82]:
tfy['fio'] = tfy['fio'].str.lower().str.translate(table)

In [83]:
tfy['DR'] = tfy['DR'].astype(str).str.split('.', expand=True)[0]

In [84]:
tfy = tfy.rename(columns={'Дата_прикрепления' : 'Дата прикрепления'})

In [85]:
tfy.head()

,Тип_ДПФС,ИД_полиса,ЕНП,ИД_МО,Способ_прикрепления,Тип_прекрепления,Дата прикрепления,Дата_открепления,FAM,IM,OT,DR,fio
0,3.0,NaN,"0148300881000084""",720045.0,1.0,1.0,"20240326""",NaN,ИЩЕНКО,ДАРЬЯ,ДМИТРИЕВНА,19961118,ищенкодарьядмитриевна
1,3.0,NaN,"0188779792000039""",720039.0,2.0,1.0,"20230614""",NaN,ДАВЛЯТЧИНА,АМИНА,РУСТАМОВНА,20221107,давлятчинааминарустамовна
2,3.0,NaN,"0190779734000028""",720030.0,1.0,1.0,"20230227""",NaN,ПОПОВ,ИЛЬЯ,ВИКТОРОВИЧ,20220915,поповильявикторович
3,3.0,NaN,"0247120826000233""",720048.0,2.0,1.0,"20240221""",NaN,ГИМАЗЕТДИНОВ,РАФАЭЛЬ,ФЛОРИТОВИЧ,19781223,гимазетдиноврафаэльфлоритович
4,3.0,NaN,"0247220882000109""",720045.0,2.0,1.0,"20241024""",NaN,ЗАРИПОВА,РАДМИЛА,ХАНИФОВНА,19771217,зариповарадмилаханифовна

In [86]:
sp_new_null = sp_new_null.merge(tfy, how='left', on=['fio', 'DR'])

In [87]:
sp_new_null.head()

,№ п/п,ФИО,Дата_рождения,СНИЛС,Телефон домашний,Телефон мобильный,Дополнительные телефоны,Район/организация,fio,DR,...,ИД_полиса,ЕНП,ИД_МО,Способ_прикрепления,Тип_прекрепления,Дата прикрепления,Дата_открепления,FAM,IM,OT
0,18,Абсолямов Фаиль Маратович,1993-04-27,148-606-419 79,NaN,NaN,NaN,Город Тюмень,абсолямовфаильмаратович,19930427,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,44,Алиев Руслан Вилаятович,1983-07-04,136-488-119 84,NaN,9.966401e+09,NaN,Тобольский район,алиеврусланвилаятович,19830704,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,74,Ануфриева Наталья Валерьевна,1987-02-23,129-272-295 71,8-922-780-0216,9.322008e+09,NaN,Вагайский район,ануфриеванатальявалерьевна,19870223,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,95,Ахминеев Андрей Иванович,1984-10-28,081-260-065 29,NaN,9.014133e+09,NaN,Город Тобольск,ахминеевандрейиванович,19841028,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,124,Барболин Мирослав Иванович,1997-09-26,151-301-644 07,+7(912) 928-0305 быв. жена Анастасия Романовна,9.821350e+09,NaN,Город Тюмень,барболинмирославиванович,19970926,...,NaN,"7250200823000151""",720009.0,2.0,1.0,"20231229""",NaN,БАРБОЛИН,МИРОСЛАВ,ИВАНОВИЧ

In [88]:
sp_new_null['ИД_МО'] = sp_new_null['ИД_МО'].astype(str)

In [89]:
sp_new_null['ИД_МО'] = sp_new_null['ИД_МО'].str.split('.', expand=True)[0]

In [90]:
sp_new_null = sp_new_null.merge(mo_name, how='left', left_on='ИД_МО', right_on='Реестровый номер')

In [91]:
sp_new_null

,№ п/п,ФИО,Дата_рождения,СНИЛС,Телефон домашний,Телефон мобильный,Дополнительные телефоны,Район/организация,fio,DR,...,ИД_МО,Способ_прикрепления,Тип_прекрепления,Дата прикрепления,Дата_открепления,FAM,IM,OT,Реестровый номер,mo_name
0,18,Абсолямов Фаиль Маратович,1993-04-27,148-606-419 79,NaN,NaN,NaN,Город Тюмень,абсолямовфаильмаратович,19930427,...,nan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,44,Алиев Руслан Вилаятович,1983-07-04,136-488-119 84,NaN,9.966401e+09,NaN,Тобольский район,алиеврусланвилаятович,19830704,...,nan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,74,Ануфриева Наталья Валерьевна,1987-02-23,129-272-295 71,8-922-780-0216,9.322008e+09,NaN,Вагайский район,ануфриеванатальявалерьевна,19870223,...,nan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,95,Ахминеев Андрей Иванович,1984-10-28,081-260-065 29,NaN,9.014133e+09,NaN,Город Тобольск,ахминеевандрейиванович,19841028,...,nan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,124,Барболин Мирослав Иванович,1997-09-26,151-301-644 07,+7(912) 928-0305 быв. жена Анастасия Романовна,9.821350e+09,NaN,Город Тюмень,барболинмирославиванович,19970926,...,720009,2.0,1.0,"20231229""",NaN,БАРБОЛИН,МИРОСЛАВ,ИВАНОВИЧ,720009,ГАУЗ ТО ГВВ
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
157,1857,Шкарин Максим Николаевич,1979-11-25,076-067-468 87,8-904-493-2376,9.026263e+09,NaN,Город Тюмень,шкаринмаксимниколаевич,19791125,...,nan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
158,1868,Штирц Валерий Александрович,1995-01-21,146-654-459 90,NaN,NaN,NaN,Викуловский район,штирцвалерийалександрович,19950121,...,nan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
159,1873,Шубин Александр Георгиевич,1989-07-08,NaN,8-989-709-71-16,NaN,NaN,Город Тюмень,шубиналександргеоргиевич,19890708,...,nan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
160,1881,Щедрин Денис Сергеевич,1989-05-09,146-080-569 58,8-919-598-83-40,NaN,NaN,Город Тюмень,щедриндениссергеевич,19890509,...,nan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
161,1891,Юлдашев Зафаржон Нуридинович,1968-11-15,106-212-674 11,NaN,9.526738e+09,NaN,Город Тюмень,юлдашевзафаржоннуридинович,19681115,...,720009,2.0,1.0,"20161202""",NaN,ЮЛДАШЕВ,ЗАФАРЖОН,НУРИДИНОВИЧ,720009,ГАУЗ ТО ГВВ

In [92]:
sp_new_new = pd.concat([sp_new_null, sp_new_pull])

In [93]:
sp_new_new.columns

Index(['№ п/п', 'ФИО', 'Дата_рождения', 'СНИЛС', 'Телефон домашний',
       'Телефон мобильный', 'Дополнительные телефоны', 'Район/организация',
       'fio', 'DR', 'Тип_ДПФС', 'ИД_полиса', 'ЕНП', 'ИД_МО',
       'Способ_прикрепления', 'Тип_прекрепления', 'Дата прикрепления',
       'Дата_открепления', 'FAM', 'IM', 'OT', 'Реестровый номер', 'mo_name'],
      dtype='object')

In [95]:
sp_new_new = sp_new_new.drop(columns=['fio', 'DR', 'Тип_ДПФС', 'ИД_полиса', 'ЕНП', 'ИД_МО',
       'Способ_прикрепления', 'Тип_прекрепления',
       'Дата_открепления', 'FAM', 'IM', 'OT', 'Реестровый номер'])

In [96]:
sp_new_new.to_excel(r'z:\Калинкина\Списокграждан_result_new.xlsx')